version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - be-rebook-auth
      - be-rebook-members
      - be-rebook-product
    ports:
      - "443:443"
      - "80:80"

  be-eureka-server:
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    env_file:
      - .env

  be-rebook-auth:
    restart: always
    build:
      context: ./rebook-auth
      dockerfile: Dockerfile
    env_file:
      - .env
    
  be-rebook-members:
    restart: always
    build:
      context: ./rebook-members
      dockerfile: Dockerfile
    env_file:
      - .env
    
  be-rebook-product:
    restart: always
    build:
      context: ./rebook-product
      dockerfile: Dockerfile
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "3306:3306"
